services:
  - type: web
    name: combined-website-analyzer
    runtime: docker
    plan: starter  # Can upgrade to standard/pro for better performance
    region: oregon  # or: frankfurt, singapore, ohio
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    
    # Environment variables
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
      - key: API_VERSION
        value: "4.0.0"
      - key: MAX_WORKERS
        value: "1"
      - key: TIMEOUT_SECONDS
        value: "300"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
    
    # Health check endpoint
    healthCheckPath: /health
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build settings
    buildFilter:
      paths:
      - main.py
      - requirements.txt
      - Dockerfile
      - render.yaml

# Optional: Add a Redis cache for caching analysis results (requires paid plan)
# - type: redis
#   name: analyzer-cache
#   plan: starter
#   maxmemoryPolicy: allkeys-lru
